version: "3"

services:
  reminder_service:
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - /media:/code/media
      - static_data:/static
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A reminder_service worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - reminder_service
    links:
      - redis
  schedule:
    build: .
    command: celery -A reminder_service beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - reminder_service
    links:
      - redis
  db:
    image: postgres:latest # указывать точную версию
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_data:/static
    depends_on:
      - reminder_service
volumes:
  data:
  media:
  static_data:
