# Generated by Django 4.1.7 on 2023-02-22 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='chart_id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user_name')),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Почта неверного формата', regex='^[-\\w\\.]+@([-\\w]+\\.)+[-\\w]{2,4}$')], verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Телефон передается в стандартном формате \n                                           +998|998 xx xxx xx xx (X - от 0 до 10)', regex='^(\\+998|998)?[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')], verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('traveled', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='company_name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone_number')),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='email')),
            ],
        ),
    ]
