# Generated by Django 4.1.7 on 2023-03-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='GENDER')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender', verbose_name='GENDER'),
        ),
    ]
