# Generated by Django 4.1.7 on 2023-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companydetail_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=9, verbose_name='GENDER'),
        ),
    ]
