# Generated by Django 4.1.7 on 2023-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gender_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='Логотип Компании'),
        ),
    ]
