# Generated by Django 4.1.7 on 2023-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='chart_id',
        ),
        migrations.AddField(
            model_name='client',
            name='inter_passport',
            field=models.CharField(default=1, max_length=9, verbose_name='international passport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(default=1, max_length=9, verbose_name='national passport'),
            preserve_default=False,
        ),
    ]
