# Generated by Django 4.1.7 on 2023-02-27 07:20

from django.db import migrations, models
import reminder_service.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_client_chart_id_client_inter_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inter_passport',
            field=models.CharField(max_length=9, validators=[reminder_service.custom_validators.passport_validator], verbose_name='international passport'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=9, validators=[reminder_service.custom_validators.passport_validator], verbose_name='national passport'),
        ),
    ]
