# Generated by Django 4.1.7 on 2023-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_client_inter_passport_alter_client_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='company_name'),
        ),
    ]
