# Generated by Django 4.1.7 on 2023-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companydetail_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='company_name'),
        ),
    ]
