# Generated by Django 4.1.7 on 2023-03-20 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_companydetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Почта неверного формата!!')], verbose_name='email'),
        ),
    ]
