# Generated by Django 4.1.7 on 2023-02-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateForChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates_for_massage', models.TextField(verbose_name='templates_for_massage')),
                ('gender', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=9, verbose_name='GENDER')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.channel', verbose_name='channel')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateTimeField(blank=True, null=True, verbose_name='sent_to')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created_at')),
                ('message', models.TextField(verbose_name='Message')),
                ('sending_status', models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status')),
                ('channels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.channel', verbose_name='channels for send')),
                ('client', models.ManyToManyField(to='accounts.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='MailingCommerceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' images')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('sending_status', models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('company_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.companydetail', verbose_name='company_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Holiday name')),
                ('date', models.DateField(verbose_name='Holiday date')),
                ('client', models.ManyToManyField(to='accounts.client')),
            ],
        ),
    ]
