# Generated by Django 4.1.7 on 2023-04-05 15:50

from django.db import migrations, models
import django.db.models.deletion
import reminder_service.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='holiday/%Y/%m/%d', validators=[reminder_service.custom_validators.validate_photo_size], verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Holiday name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Holiday date')),
                ('congratulation', models.TextField(verbose_name='congratulate_text')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gender', verbose_name='GENDER')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', validators=[reminder_service.custom_validators.validate_photo_size], verbose_name=' Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateForChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('Коммерческое предложение', 'Коммерческое предложение'), ('День рождения', 'День рождения'), ('Праздники', 'Праздники')], max_length=255, verbose_name='template_name')),
                ('templates_for_massage', models.TextField(verbose_name='templates_for_massage')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.channel', verbose_name='channel')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gender', verbose_name='GENDER')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateTimeField(blank=True, null=True, verbose_name='sent_to')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('message', models.TextField(verbose_name='Message')),
                ('sending_status', models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status')),
                ('channels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.channel', verbose_name='channels for send')),
                ('client', models.ManyToManyField(to='accounts.client', verbose_name='Client')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminder.holiday', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='MailingCommerceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('sending_status', models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city', verbose_name='City')),
                ('company_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companydetail', verbose_name='company_detail')),
                ('photo', models.ManyToManyField(blank=True, to='reminder.multipleimage')),
            ],
        ),
    ]
