# Generated by Django 4.1.7 on 2023-04-06 08:42

from django.db import migrations, models
import reminder_service.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', validators=[reminder_service.custom_validators.validate_photo_size], verbose_name=' Изображение или видео'),
        ),
    ]
