# Generated by Django 4.1.7 on 2023-02-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcommerceoffer',
            name='sending_status',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='sending_status'),
        ),
    ]
