# Generated by Django 4.1.7 on 2023-03-09 10:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='congratulation',
            field=models.TextField(default='hello', verbose_name='congratulation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(default='1998-09-15', verbose_name='Holiday date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='company_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.companydetail', verbose_name='company_detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=ckeditor.fields.RichTextField(default='hello', verbose_name='message'),
            preserve_default=False,
        ),
    ]
