# Generated by Django 4.1.7 on 2023-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='url'),
        ),
    ]
