# Generated by Django 4.1.7 on 2023-02-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_mailingcommerceoffer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='congratulation',
            field=models.TextField(blank=True, null=True, verbose_name='congratulation'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Holiday date'),
        ),
    ]
