# Generated by Django 4.1.7 on 2023-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_holiday_congratulation_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, default='image.jpg', upload_to='media/holiday//%Y/%m/%d', verbose_name=' images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
