# Generated by Django 4.1.7 on 2023-04-06 10:48

from django.db import migrations, models
import reminder_service.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_multipleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', validators=[reminder_service.custom_validators.validate_photo_size], verbose_name=' Изображение'),
        ),
    ]
