# Generated by Django 4.1.7 on 2023-03-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_holiday_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='GENDER')),
            ],
        ),
        migrations.AlterField(
            model_name='holiday',
            name='congratulation',
            field=models.TextField(verbose_name='congratulate_text'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Holiday name'),
        ),
        migrations.AlterField(
            model_name='templateforchannel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.gender', verbose_name='GENDER'),
        ),
    ]
