# Generated by Django 4.1.7 on 2023-02-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_holiday_congratulation_alter_holiday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(choices=[('', ''), ('День рождение', 'День рождение'), ('Новый год', 'Новый год'), ('Навруз', 'Навруз'), ('День почестей', 'День почестей'), ('День Независимости', 'День Независимости'), ('День конституции', 'День конституции'), ('Рамазан Хайит', 'Рамазан Хайит'), ('Курбан Хайит', 'Курбан Хайит'), ('Международный день туризма', 'Международный день туризма'), ('8 марта', '8 марта')], max_length=100, verbose_name='Holiday name'),
        ),
        migrations.AlterField(
            model_name='templateforchannel',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=9, verbose_name='GENDER'),
        ),
    ]
