# Generated by Django 4.1.7 on 2023-04-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_multipleimage_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingcommerceoffer',
            old_name='photo',
            new_name='media',
        ),
    ]
