# Generated by Django 4.1.7 on 2023-02-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_holiday_name_alter_templateforchannel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='client',
        ),
    ]
