# Generated by Django 4.1.7 on 2023-03-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gender_alter_client_gender'),
        ('reminder', '0004_gender_alter_holiday_congratulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateforchannel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender', verbose_name='GENDER'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
