# Generated by Django 4.1.7 on 2023-03-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gender_alter_client_gender'),
        ('reminder', '0005_alter_templateforchannel_gender_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcommerceoffer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city', verbose_name='City'),
        ),
    ]
