# Generated by Django 4.1.7 on 2023-04-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_rename_photo_mailingcommerceoffer_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimage',
            name='video',
        ),
    ]
