# Generated by Django 4.1.7 on 2023-02-27 12:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_holiday_image_alter_result_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='message'),
        ),
    ]
