# Generated by Django 4.1.7 on 2023-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_mailingcommerceoffer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/holiday//%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' Изображение'),
        ),
    ]
