# Generated by Django 4.1.7 on 2023-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_alter_holiday_image_alter_mailingcommerceoffer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMailingCommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('sending_status', models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.RemoveField(
            model_name='mailingcommerceoffer',
            name='sending_status',
        ),
    ]
