# Generated by Django 4.1.7 on 2023-04-06 13:24

from django.db import migrations, models
import reminder_service.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_multipleimage_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', validators=[reminder_service.custom_validators.validate_video_extension], verbose_name=' Видео')),
            ],
        ),
        migrations.RemoveField(
            model_name='multipleimage',
            name='video',
        ),
    ]
