# Generated by Django 4.1.7 on 2023-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_alter_mailingcommerceoffer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
    ]
