# Generated by Django 4.1.7 on 2023-04-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_multiplevideo_remove_multipleimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcommerceoffer',
            name='video',
            field=models.ManyToManyField(blank=True, to='reminder.multiplevideo'),
        ),
    ]
