# Generated by Django 4.1.7 on 2023-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_finalmailingcommerce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateforchannel',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='template_name'),
            preserve_default=False,
        ),
    ]
