# Generated by Django 4.1.7 on 2023-03-04 20:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_alter_mailingcommerceoffer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
