# Generated by Django 4.1.7 on 2023-03-05 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_alter_mailingcommerceoffer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='message'),
        ),
    ]
