# Generated by Django 4.1.7 on 2023-03-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_templateforchannel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateforchannel',
            name='name',
            field=models.CharField(choices=[('', ''), ('Коммерческое предложение', 'Коммерческое предложение'), ('День рождения', 'День рождения'), ('Праздники', 'Праздники')], max_length=255, verbose_name='template_name'),
        ),
    ]
