# Generated by Django 4.1.7 on 2023-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0010_alter_templateforchannel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/holiday/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
