# Generated by Django 4.1.7 on 2023-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0011_alter_holiday_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name=' Изображение'),
        ),
    ]
