# Generated by Django 4.1.7 on 2023-03-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0012_alter_mailingcommerceoffer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmailingcommerce',
            name='mailing',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='reminder.mailingcommerceoffer', verbose_name='mailing_id'),
            preserve_default=False,
        ),
    ]
