# Generated by Django 4.1.7 on 2023-03-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0013_finalmailingcommerce_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmailingcommerce',
            name='mailing',
        ),
    ]
