# Generated by Django 4.1.7 on 2023-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0014_remove_finalmailingcommerce_mailing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalMailingCommerce',
        ),
        migrations.AddField(
            model_name='mailingcommerceoffer',
            name='sending_status',
            field=models.CharField(blank=True, default=False, max_length=90, null=True, verbose_name='sending_status'),
        ),
    ]
