# Generated by Django 4.1.7 on 2023-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0016_holiday_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Holiday date'),
        ),
    ]
