# Generated by Django 4.1.7 on 2023-03-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_user_name'),
        ('reminder', '0017_alter_holiday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateforchannel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gender', verbose_name='GENDER'),
        ),
    ]
