# Generated by Django 4.1.7 on 2023-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0019_alter_holiday_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name=' Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='mailingcommerceoffer',
            name='photo',
        ),
        migrations.AddField(
            model_name='mailingcommerceoffer',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='reminder.multipleimage'),
        ),
    ]
