# Generated by Django 4.1.7 on 2023-03-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0020_multipleimage_remove_mailingcommerceoffer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcommerceoffer',
            name='photo',
            field=models.ManyToManyField(blank=True, to='reminder.multipleimage'),
        ),
        migrations.AlterField(
            model_name='multipleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name=' Изображение'),
        ),
    ]
